# Generated by Django 5.0.2 on 2024-04-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_alter_memo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
