# Generated by Django 5.0.2 on 2024-03-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_goal_type_task'),
    ]

    operations = [
    ]
