# Generated by Django 5.0.2 on 2024-03-31 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_remove_task_goal_type_long_term_medium_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium_term',
            name='user',
        ),
        migrations.RemoveField(
            model_name='short_term',
            name='user',
        ),
        migrations.DeleteModel(
            name='long_term',
        ),
        migrations.DeleteModel(
            name='medium_term',
        ),
        migrations.DeleteModel(
            name='short_term',
        ),
    ]
