# Generated by Django 5.0.2 on 2024-05-15 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_task_event_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
