# Generated by Django 5.0.2 on 2024-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0003_fixedexpense_variableexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
    ]
