# Generated by Django 5.0.2 on 2024-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0005_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=10),
        ),
    ]
