# Generated by Django 5.0.2 on 2024-05-15 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0006_alter_accountbook_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedexpense',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='variableexpense',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variableexpense',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
