# Generated by Django 5.0.2 on 2024-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
