# Generated by Django 5.0.2 on 2024-05-06 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_alter_value_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
