# Generated by Django 5.0.2 on 2024-03-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_end_time_remove_task_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('A', 'Aborted'), ('P', 'Postponed')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('A', 'High'), ('B', 'Medium'), ('C', 'Low')], default='B', max_length=1),
        ),
    ]
