# Generated by Django 5.0.2 on 2024-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_created_at_remove_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', '進行中'), ('completed', '完了')], default='in_progress', max_length=12, verbose_name='進行状況'),
        ),
    ]
