# Generated by Django 5.0.2 on 2024-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_completed_at_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='', max_length=10),
        ),
    ]
